### ISSUE TITLE
Handling self-signed certs

### ISSUE THREAD

**Issue by eggzotic** [insinfo/essential_rest#1]
Is there any way to handle self-signed certs with essential_rest? e.g. I am developing against some REST APIs installed on a home VM. Currently I am getting error:
flutter: RestClientGeneric@getAll HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: ok(handshake.cc:354))

It seems that the way to bypass this with HttpClient is to set the badCertificateCallback to return true. Can we get at that from  essential_rest? Thx.

**Comment by eggzotic** [comment]
Nvm, I realise the solution to my problem is not specific to this package, and instead is to be found in the final solution by pepie at https://github.com/flutter/flutter/issues/19588

**Comment by insinfo** [comment]
@eggzotic 
I have been very busy, so I just answered now, well this is the solution at the moment, but if you want to do a PR I am available to merge


```dart
class MyHttpOverrides extends HttpOverrides {
  @override
  HttpClient createHttpClient(SecurityContext securityContext) {
    return new HttpClient()
      .. badCertificateCallback = ...;
  }

void main() {
  HttpOverrides.global = new MyHttpOverrides();
  runApp(...)
}

```
